export const events = [
  {
    id: "stem-workshop-kids",
    title: "Taller STEM para Niños",
    description:
      "Empoderando a la próxima generación de innovadores con experiencias prácticas en robótica, programación básica e ingeniería creativa.",
    date: "24 Oct",
    location: "Centro de Innovación Tech",
    type: "Taller",
    spotsLeft: 12,
    status: "activo",
    image: "https://images.unsplash.com/photo-1581092918056-0c4c3acd3789?w=800&q=80",
    institution: "Tech Academy SF",
    sponsors: ["Google", "Microsoft", "Cisco"],
    volunteersNeeded: 50,
    volunteersJoined: 38,
    studentsGoal: 200,
    agenda: [
      { time: "09:00 AM", title: "Orientación de Voluntarios", description: "Distribución de materiales y asignación de roles." },
      { time: "10:00 AM", title: "Introducción a la Lógica", description: "Presentación sobre cómo piensan y resuelven problemas las computadoras." },
      { time: "11:30 AM", title: "Robótica Práctica", description: "Ensamblaje y programación básica de movimiento." },
      { time: "01:00 PM", title: "Demo Final y Premios", description: "Los equipos presentan sus proyectos y reciben certificados." },
    ],
    about:
      "Este taller ofrece a niños de primaria experiencias prácticas en programación básica, robótica y principios de ingeniería. Nuestro objetivo es despertar la curiosidad y fomentar el amor por la ciencia y la tecnología desde temprana edad.",
    fullLocation: "450 Innovation Way, Suite 200, San Francisco, CA 94103",
  },
  {
    id: "liderazgo-juvenil",
    title: "Cumbre de Liderazgo Juvenil 2024",
    description:
      "Empoderando a la próxima generación de líderes para resolver desafíos locales mediante la innovación y la acción comunitaria.",
    date: "05 Nov",
    location: "Municipalidad",
    type: "Conferencia",
    spotsLeft: 25,
    status: "activo",
    image: "https://images.unsplash.com/photo-1524178232363-1fb2b075b655?w=800&q=80",
    institution: "Universidad Nacional",
    sponsors: ["Banco Nacional", "Fundación Educativa"],
    volunteersNeeded: 30,
    volunteersJoined: 18,
    studentsGoal: 150,
    agenda: [
      { time: "08:30 AM", title: "Registro y bienvenida", description: "Check-in de participantes y voluntarios." },
      { time: "09:00 AM", title: "Panel de Líderes", description: "Charla con líderes comunitarios locales." },
      { time: "11:00 AM", title: "Talleres grupales", description: "Sesiones de trabajo por temáticas." },
      { time: "02:00 PM", title: "Presentaciones finales", description: "Cada grupo presenta sus propuestas de impacto." },
    ],
    about:
      "La Cumbre de Liderazgo Juvenil reúne a jóvenes de toda la región para desarrollar habilidades de liderazgo, trabajo en equipo y pensamiento crítico.",
    fullLocation: "Av. Principal 1200, Sala de Conferencias, Lima",
  },
  {
    id: "formacion-digital",
    title: "Formación Digital para Adultos Mayores",
    description:
      "Reduciendo la brecha digital enseñando herramientas básicas de internet, videollamadas y seguridad en línea a adultos mayores.",
    date: "12 Nov",
    location: "Centro Comunitario Norte",
    type: "Programa",
    spotsLeft: 8,
    status: "activo",
    image: "https://images.unsplash.com/photo-1529070538774-1843cb3265df?w=800&q=80",
    institution: "Centro Comunitario Norte",
    sponsors: ["Claro", "Entel"],
    volunteersNeeded: 20,
    volunteersJoined: 15,
    studentsGoal: 60,
    agenda: [
      { time: "10:00 AM", title: "Uso del smartphone", description: "Cómo hacer llamadas, mensajes y fotos." },
      { time: "11:30 AM", title: "Internet y navegación segura", description: "Cómo buscar información y evitar estafas." },
      { time: "01:00 PM", title: "Videollamadas", description: "Práctica con Zoom y WhatsApp Video." },
    ],
    about:
      "Programa de alfabetización digital diseñado específicamente para adultos mayores. Voluntarios jóvenes acompañan a los participantes en un ambiente cálido y sin presión.",
    fullLocation: "Jr. Los Cedros 450, Lima",
  },
  {
    id: "charla-medio-ambiente",
    title: "Charla: Medio Ambiente y Acción Local",
    description:
      "Aprende cómo reducir tu huella de carbono y vivir de manera más sostenible con expertos en medio ambiente.",
    date: "18 Nov",
    location: "Biblioteca Municipal",
    type: "Charla",
    spotsLeft: 40,
    status: "borrador",
    image: "https://images.unsplash.com/photo-1497436072909-60f360e1d4b1?w=800&q=80",
    institution: "ONG EcoVida",
    sponsors: ["Natura", "BioMarket"],
    volunteersNeeded: 10,
    volunteersJoined: 6,
    studentsGoal: 100,
    agenda: [
      { time: "06:00 PM", title: "Charla principal", description: "Conferencia sobre cambio climático local." },
      { time: "07:00 PM", title: "Panel de preguntas", description: "Interacción con los expertos." },
      { time: "07:30 PM", title: "Compromisos colectivos", description: "Firma de compromisos de acción." },
    ],
    about:
      "Una charla abierta a la comunidad para entender el impacto del cambio climático a nivel local y cómo cada persona puede contribuir.",
    fullLocation: "Av. Cultura 300, Sala Principal, Cusco",
  },
  {
    id: "mentoria-stem-colegios",
    title: "Mentoría STEM en Colegios Públicos",
    description:
      "Voluntarios profesionales en ciencia, tecnología, ingeniería y matemáticas visitan colegios públicos para inspirar a estudiantes.",
    date: "22 Nov",
    location: "Colegio Nacional San Marcos",
    type: "Voluntariado Educativo",
    spotsLeft: 5,
    status: "activo",
    image: "https://images.unsplash.com/photo-1509062522246-3755977927d7?w=800&q=80",
    institution: "Colegio Nacional San Marcos",
    sponsors: ["Intel", "SAP"],
    volunteersNeeded: 40,
    volunteersJoined: 38,
    studentsGoal: 300,
    agenda: [
      { time: "08:00 AM", title: "Briefing de voluntarios", description: "Asignación de aulas y materiales." },
      { time: "09:00 AM", title: "Sesiones en aula", description: "Charlas y demos en cada salón." },
      { time: "11:00 AM", title: "Feria de proyectos", description: "Estudiantes presentan ideas STEM." },
    ],
    about:
      "Programa que conecta a profesionales de STEM con estudiantes de colegios públicos. Los voluntarios comparten su experiencia y motivan a los jóvenes.",
    fullLocation: "Jr. Universitaria 1500, Lima",
  },
  {
    id: "hackathon-social",
    title: "Hackathon de Impacto Social",
    description:
      "48 horas para desarrollar soluciones tecnológicas a problemas reales de nuestra comunidad. Equipos de hasta 5 personas.",
    date: "06 Dic",
    location: "Hub de Innovación",
    type: "Evento STEM",
    spotsLeft: 60,
    status: "borrador",
    image: "https://images.unsplash.com/photo-1504384308090-c894fdcc538d?w=800&q=80",
    institution: "Universidad de Ingeniería",
    sponsors: ["AWS", "GitHub", "Atlassian"],
    volunteersNeeded: 15,
    volunteersJoined: 7,
    studentsGoal: 120,
    agenda: [
      { time: "Día 1 - 09:00 AM", title: "Apertura y formación de equipos", description: "Presentación de retos." },
      { time: "Día 1 - 11:00 AM", title: "Hackathon comienza", description: "48 horas de desarrollo." },
      { time: "Día 3 - 09:00 AM", title: "Presentaciones finales", description: "Cada equipo presenta su solución." },
      { time: "Día 3 - 12:00 PM", title: "Premiación", description: "Entrega de premios y reconocimientos." },
    ],
    about:
      "Un hackathon enfocado en crear soluciones tecnológicas para problemas sociales locales: educación, salud, medio ambiente y acceso a servicios.",
    fullLocation: "Av. Universitaria 800, Lima",
  },
];

export const volunteers = [
  { id: "v1", name: "María García", email: "maria@email.com", eventId: "stem-workshop-kids", event: "Taller STEM para Niños", role: "Instructor", status: "aprobado", hours: 8, joinedAt: "15 Oct 2024", initials: "MG", color: "bg-amber-400" },
  { id: "v2", name: "Carlos Quispe", email: "carlos@email.com", eventId: "liderazgo-juvenil", event: "Cumbre de Liderazgo Juvenil", role: "Facilitador", status: "aprobado", hours: 6, joinedAt: "18 Oct 2024", initials: "CQ", color: "bg-blue-400" },
  { id: "v3", name: "Ana Torres", email: "ana@email.com", eventId: "formacion-digital", event: "Formación Digital", role: "Asistente", status: "pendiente", hours: 0, joinedAt: "20 Oct 2024", initials: "AT", color: "bg-purple-400" },
  { id: "v4", name: "Luis Mendoza", email: "luis@email.com", eventId: "stem-workshop-kids", event: "Taller STEM para Niños", role: "Mentor", status: "aprobado", hours: 8, joinedAt: "16 Oct 2024", initials: "LM", color: "bg-emerald-400" },
  { id: "v5", name: "Rosa Huanca", email: "rosa@email.com", eventId: "mentoria-stem-colegios", event: "Mentoría STEM en Colegios", role: "Instructor", status: "pendiente", hours: 0, joinedAt: "21 Oct 2024", initials: "RH", color: "bg-rose-400" },
  { id: "v6", name: "Diego Paredes", email: "diego@email.com", eventId: "hackathon-social", event: "Hackathon de Impacto Social", role: "Coordinador", status: "rechazado", hours: 0, joinedAt: "10 Oct 2024", initials: "DP", color: "bg-slate-400" },
  { id: "v7", name: "Sofia Ramos", email: "sofia@email.com", eventId: "charla-medio-ambiente", event: "Charla: Medio Ambiente", role: "Moderador", status: "aprobado", hours: 3, joinedAt: "12 Oct 2024", initials: "SR", color: "bg-teal-400" },
  { id: "v8", name: "Jhon Vargas", email: "jhon@email.com", eventId: "liderazgo-juvenil", event: "Cumbre de Liderazgo Juvenil", role: "Asistente", status: "pendiente", hours: 0, joinedAt: "22 Oct 2024", initials: "JV", color: "bg-orange-400" },
  { id: "v9", name: "Paola Medina", email: "paola@email.com", eventId: "stem-workshop-kids", event: "Taller STEM para Niños", role: "Instructor", status: "aprobado", hours: 8, joinedAt: "14 Oct 2024", initials: "PM", color: "bg-pink-400" },
  { id: "v10", name: "Ernesto Silva", email: "ernesto@email.com", eventId: "formacion-digital", event: "Formación Digital", role: "Asistente", status: "pendiente", hours: 0, joinedAt: "23 Oct 2024", initials: "ES", color: "bg-cyan-400" },
];

export const institutions = [
  { id: "i1", name: "Colegio Nacional San Marcos", type: "Colegio", city: "Lima", contact: "Prof. Ramírez", email: "smarcos@edu.pe", status: "activo", eventsHosted: 4, studentsImpacted: 850, since: "Mar 2023" },
  { id: "i2", name: "Universidad Nacional de Ingeniería", type: "Universidad", city: "Lima", contact: "Dr. Castillo", email: "uni@uni.edu.pe", status: "activo", eventsHosted: 6, studentsImpacted: 2100, since: "Ene 2023" },
  { id: "i3", name: "Centro Comunitario Norte", type: "Centro Comunitario", city: "Lima", contact: "Ana Flores", email: "ccnorte@org.pe", status: "activo", eventsHosted: 3, studentsImpacted: 180, since: "Jun 2023" },
  { id: "i4", name: "Colegio María Auxiliadora", type: "Colegio", city: "Cusco", contact: "Hna. Patricia", email: "maria.aux@edu.pe", status: "solicitud", eventsHosted: 0, studentsImpacted: 0, since: "—" },
  { id: "i5", name: "PUCP — Pontificia Universidad", type: "Universidad", city: "Lima", contact: "Mg. Herrera", email: "pucp@pucp.edu.pe", status: "activo", eventsHosted: 8, studentsImpacted: 3200, since: "Nov 2022" },
  { id: "i6", name: "IE Gran Unidad Escolar", type: "Colegio", city: "Arequipa", contact: "Prof. Salas", email: "gue@edu.pe", status: "solicitud", eventsHosted: 0, studentsImpacted: 0, since: "—" },
  { id: "i7", name: "Academia Pre-Universitaria Trilce", type: "Centro Educativo", city: "Lima", contact: "Lic. Vega", email: "trilce@trilce.pe", status: "inactivo", eventsHosted: 2, studentsImpacted: 420, since: "Ago 2023" },
  { id: "i8", name: "ONG Futuro Digital", type: "ONG", city: "Trujillo", contact: "Carlos Nieto", email: "ong@futurodi.pe", status: "activo", eventsHosted: 5, studentsImpacted: 960, since: "Feb 2023" },
];

export const reviews = [
  { id: "r1", eventId: "stem-workshop-kids", author: "María García", role: "Voluntaria", rating: 5, comment: "Una experiencia increíble. Los niños estaban muy entusiasmados y aprendieron muchísimo. La organización fue impecable.", date: "26 Oct 2024" },
  { id: "r2", eventId: "stem-workshop-kids", author: "Tech Academy SF", role: "Institución", rating: 5, comment: "Excelente coordinación con el equipo de voluntarios. Esperamos repetir el evento el próximo semestre.", date: "27 Oct 2024" },
  { id: "r3", eventId: "liderazgo-juvenil", author: "Carlos Quispe", role: "Voluntario", rating: 4, comment: "Muy buen evento. Los panelistas fueron muy inspiradores. Podría mejorar la logística del registro.", date: "07 Nov 2024" },
  { id: "r4", eventId: "formacion-digital", author: "Ana Torres", role: "Voluntaria", rating: 5, comment: "Ver la emoción de los adultos mayores al aprender a videollamar a sus familias fue muy gratificante.", date: "14 Nov 2024" },
  { id: "r5", eventId: "mentoria-stem-colegios", author: "Colegio Nacional San Marcos", role: "Institución", rating: 5, comment: "Los voluntarios llegaron muy bien preparados. Los estudiantes quedaron muy motivados con las carreras STEM.", date: "24 Nov 2024" },
];

export const stats = {
  totalVolunteers: "10,482+",
  eventsHosted: 542,
  studentsReached: "25.6k",
  institutionsBenefited: 87,
  volunteerHours: "48,900",
};
